services:
  web2lectures:
    image: postgres:16-alpine
    ports:
      # HOST:CONTAINER
      - "6543:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./create-database-users.sql:/docker-entrypoint-initdb.d/create-database-users.sql
      - ./create-database-sales.sql:/docker-entrypoint-initdb.d/create-database-sales.sql
    networks:
      - backend

  pgadmin-lectures:
    image: dpage/pgadmin4:9.3.0
    ports:
      - "8123:80"
      - "8443:443"
    environment:
      - PGADMIN_DEFAULT_EMAIL=web@ufop.edu.br
      - PGADMIN_DEFAULT_PASSWORD=123456
    networks:
      - backend

networks:
  frontend:
  backend: