spring.application.name=User Service


# Porta do servidor
server.port=3000

# Profile de configuração ativo
# spring.profiles.default=

# Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:6543/ticket_users
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

# Configura��es do Eureka Client
eureka.client.serviceUrl.defaultZone=http://nameserver:8761/eureka