###
@urlServer = http://localhost:3000

###
GET {{urlServer}}/users/status
###

GET {{urlServer}}/ccn

###
POST {{urlServer}}/ccn
Content-Type: application/json

{
  "name": "Master"
}

###
GET {{urlServer}}/users

###
POST {{urlServer}}/users
Content-Type: application/json

{
  "name": "Fernando",
  "creditCardNetworkId": "5dd30405-e5cc-42f6-8c2f-35aa70e55ce3",
  "email": "fernando@web.ufop.edu.br",
  "password": "123456"
}

###
GET {{urlServer}}/users/961ba1a5-98e4-46a8-bc31-e463bb8b5cbe
















