###
@urlServer = http://localhost:3000

###
GET {{urlServer}}/users/status
###

GET {{urlServer}}/ccn

###
POST {{urlServer}}/ccn
Content-Type: application/json

{
  "name": ""
}

###

GET {{urlServer}}/users

###
POST {{urlServer}}/users
Content-Type: application/json

{
  "name": "Fernando",
  "creditCardNetworkId": "ca507654-5b29-4900-bb1b-5740e74ba1db"
}
















