# version: '3' -> obsoleto
services:
  tickets-nameserver:
    image: tickets-nameserver:latest
    ports:
      # HOST:CONTAINER
      - "8761:8761"
    networks:
      - backend 
      
  tickets-gateway:
    image: tickets-gateway:latest
    ports:
      # HOST:CONTAINER
      - "8080:8080"
    networks:
      - backend 
      
  tickets-users:
    image: tickets-users:latest
    ports:
      # HOST:CONTAINER
      - "3000:3000"
    networks:
      - backend 
      
  tickets-sales:
    image: tickets-sales:latest
    ports:
      - "4000:4000"
    networks:
      - backend 

  tickets-notifications:
    image: tickets-notifications:latest
    ports:
      # HOST:CONTAINER
      - "5000:5000"
    networks:
      - backend 

  tickets-frontend:
    image: tickets-frontend:latest
    ports:
      - "5173:5173"
    networks:
      - frontend 

networks:
  frontend:
  backend: